version: '3.8'
services:
  pgdatabase:
    container_name: postgres_db
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=wasterwater_overflows
    volumes: 
      - ./wasterwater_overflows_postgres_data:/var/lib/postgres/data/ny_taxi
    ports: 
      - '5432:5432'
    networks:
      - wasterwater_overflows_network
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports: 
      - '8080:80'
    networks:
      - wasterwater_overflows_network


volumes:
  wasterwater_overflows_postgres_data:
  local_pgdata:
  pgadmin-data:

networks:
  wasterwater_overflows_network:
    driver: bridge
